### PR TITLE
Updated travis configuration for Swift 3

### PR DESCRIPTION
**Pull request by andreyrd**
This should hopefully make tests for the Swift 3 branch pass now.

### CODE REVIEW

**Comment by rytonbay** [comment]
Thank you andreyrd for making this pull request so I didn't have to, I need this library to work with Swift 3 for my project.  Thanks Haneke for making it happen ASAP!

**Comment by rytonbay** [comment]
Thanks!!

**Comment by dcharbonnier** [comment]
but it does not work :-(

**Comment by dcharbonnier** [comment]
can you check ? https://travis-ci.org/Haneke/HanekeSwift/builds/166684403

**Comment by andreyrd** [comment]
Looks like it's similar to ec5fb9761d60b0894177f097c92e2af3b4d2230b

**Pull request merged**
