### PR TITLE
Swift 2.3 support

### PR DESCRIPTION
**Pull request by chadmoone**
I've made a branch to support Swift 2.3.  The changes were pretty minor.  You may want to take a look at the `UIImage+Haneke` changes, as they involve some force unwrapping, and I wasn't sure how you thought this should be handled (might require changing the method signature).

I'm guess that you will not want to `master`, but if you would like to create a `swift-2.3` branch, I can close this and submit a new PR pointing there.

This should address #331.

### CODE REVIEW

**Comment by dcharbonnier** [comment]
Targeting swift 3 now

**Comment by chadmoone** [comment]
That's great, but I think it's a mistake to skip 2.3. A lot of large swift apps (several of ours, for example) have not been able to update all the way to 3.0 yet, and the changes for swift 2.3 are very manageable. IMHO that's something the library needs to support.

**Comment by ArtSabintsev** [comment]
+1 for Swift2.3 support. 

Simply add a separate branch at 2.3 that contains everything up to the last 2.2 commit and don't add any more features to 2.3. It'll incentivize many people to move to Swift 3 for new features. As @chadmoone said, bigger companies such as ours, cannot move to Swift 3, but we depend on OSS libraries such as this one to get the job done.

Will you reconsider?

**Comment by anscho** [comment]
For reference on an alternative approach, Alamofire used a minor version to address 2.3 support, while using the major version to address 3.0 support: https://github.com/Alamofire/Alamofire/releases/tag/3.5.0

**Comment by pcsforeducation** [comment]
+1 for Swift 2.3. This is the last library we rely on that's not 2.3 compatible. I'm going to move us to Swift 3.0 in the near-ish future, but not being able to use Xcode 8 right now is pretty annoying. 

That said, a fork with any of these 4 2.3 PRs isn't the worst thing until we're ready to go to 3.0.

**Comment by samuel-mellert** [comment]
+1 for Swift2.3 support.

If you are using Alamofire as a network library and still have to support iOS 8, you can't just hop onto the Swift 3.0 train. Therefor it is very important to support both flavours of Swift 2.3 & 3.0. It is really sad to see that this fact gets neglected by so many people.

**Comment by dcharbonnier** [comment]
https://github.com/Haneke/HanekeSwift/pull/350

**Pull request closed without merging**
