### PR TITLE
Feature/apple tv

### PR DESCRIPTION
**Pull request by dcharbonnier**
fix #232 and #231

fix also a warning on the test linking

### CODE REVIEW

**Comment by hpique** [comment]
Looks good! Would you mind modifying the tvOS scheme so that it also runs the unit tests?

**Comment by dcharbonnier** [comment]
ok, I will need to duplicate the target but why not, not sure it can make any difference, the tvOS is a subset of iOS

**Comment by dcharbonnier** [comment]
never tried that but it looks like it work just setting the test target on the tvos target, weird the tests are not supposed to compile the tvOS target

image

**Comment by dcharbonnier** [comment]
to run them on travis I think it's better to do an other PR with more changes on the travis file, I create an issue

**Pull request merged**
