### PR TITLE
Swift 2.0 - Xcode7GM 

### PR DESCRIPTION
**Pull request by rromanchuk**

### CODE REVIEW

**Comment by keith** [comment]
It would be awesome if this could be merged so that we could ship using an official release!

**Comment by benhanzl** [comment]
I've been using this branch for quite some time without any issues.

**Comment by meteochu** [comment]
Actually, it'd be better if we merged the master branch instead of the swift-2.0 branch from my fork. I updated the CocoaPods podspec and Carthage build release to use the latest build. https://github.com/meteochu/HanekeSwift

**Comment by papertigers** [comment]
@hpique can we get this merged?

**Comment by ded** [comment]
XCode 7 left beta yesterday. It's probably a good time to figure out the actual plan. At minimum I would merge the other branch into this repo (maybe not into master), but at least it will be in a more findable place

**Comment by kkpoon** [comment]
Time to merge, please.

**Comment by mohwaili** [comment]
Merge pleeeeeeeease!

**Comment by hpique** [comment]
Thanks for making this branch available @rromanchuk. Unfortunately I couldn't merge it as there were some unrelated commits, and I had very limited time to work on Haneke. I will look at them later. In the meantime, Swift 2.0 support is now on master.

**Pull request closed without merging**
