### PR TITLE
Make Fetcher methods public for subclassing.

### PR DESCRIPTION
**Pull request by jordanhamill**
I can't create a `Fetcher` subclass outside of the `Haneke` module and I seen that #143 had been closed.

### CODE REVIEW

**Comment by vvrinne** [comment]
I was just wondering if I should report this or if I am just missing something about how to create a custom fetcher. I'm running Haneke through cocoapods and thus it is in a separate project from my application. Any other way to create a custom fetcher other than manually changing the methods to public and subclassing Fetcher?

**Comment by preble** [comment]
As far as I can tell this is the intended pattern for custom Fetchers. I'd like to see this PR merged.

**Comment by harryworld** [comment]
+1

**Comment by preble** [comment]
This PR should be closed; #224, which had the same changes, has been merged.

**Pull request closed without merging**
