### PR TITLE
Fix project compilation with Swift 2.3 and Xcode 8

### PR DESCRIPTION
**Pull request by AlbertoGuerreroMartin**
Fixed project compilation using Xcode's 8 syntax updater for Swift 2.3.

### CODE REVIEW

**Comment by alpennec** [comment]
Any update on this?

**Comment by dcharbonnier** [comment]
hi, the problem is that the tests are not passing on this PR but yes it would be nice to fix them and to merge, thx

**Comment by gblotter** [comment]
@AlbertoGuerreroMartin - In order for the CI stuff to pass, you'll need to edit the .travis.yml file to have osx_image: xcode8

**Comment by AlbertoGuerreroMartin** [comment]
@gblotter done! I've also seen "language: objective-c" on .travis.yml file. Should it be "swift" instead of "objective-c"?

**Comment by gblotter** [comment]
@AlbertoGuerreroMartin no, you can leave that... Did you push?  The tests should've re-run...

**Comment by gblotter** [comment]
Needs to be run again... it died checking out a dependency

**Comment by gblotter** [comment]
@dcharbonnier could you re-run the travis job, please? :)

**Comment by dcharbonnier** [comment]
If you make a change it will run again

Le mar. 9 août 2016 18:05, Geoffrey Blotter <notifications@github.com> a
écrit :

**Comment by gblotter** [comment]
@dcharbonnier what change would you like @AlbertoGuerreroMartin to make...?

**Comment by AlbertoGuerreroMartin** [comment]
@dcharbonnier @gblotter maybe add a line break on README.md or similar... on my local `carthage bootstrap` is running smoothly

**Comment by gblotter** [comment]
@dcharbonnier my bad... I thought you were the owner... It looks like @hpique, or @joanromano, or @Lascorbe, or @oriolblanc might be?  Can one of you guys help us out?  

I know travis builds can be kicked off w/o having to change code... I just hate to have @AlbertoGuerreroMartin commit a silly line break to get the tests to run again.

**Comment by joanromano** [comment]
Restarted guys, sorry for the inconvenience.

**Comment by alpennec** [comment]
Any update? Thanks

**Comment by gblotter** [comment]
Also submitted a PR... w/ changes to the Travis-CI build setting AND to the OHHTTPStubs framework version to one that supports Swift 2.3 as well #344.  We'll see if we can get 1 of the 3 pushed through...

**Comment by dcharbonnier** [comment]
Targeting swift 3 now

**Comment by dcharbonnier** [comment]
https://github.com/Haneke/HanekeSwift/pull/350

**Pull request closed without merging**
