### PR TITLE
Convert to Swift 3 with minor changes of internal methods to conform to Swift 3 syntax

### PR DESCRIPTION
**Pull request by jasonnoahchoi**
Some methods such as `pathForKey(key: String)` have been changed to `path(forKey key: String)`

Changed name of `Cache` class to `HanekeCache` in order to not conflict with potential Swift3 `Cache` class which stems from `NSCache`

### CODE REVIEW

**Comment by lukeivers** [comment]
Fwiw, I was using this fork and it was working just fine for me in Swift 3 (now using a different image library altogether, but this fork worked great for Haneke + Swift 3).

**Comment by jasonnoahchoi** [comment]
Thanks @lukeivers We're using it for our live project and so far no issues!

**Comment by joshuamanns** [comment]
@lukeivers Curious as to which image library your switched to. Looking for something more stable in my project

**Comment by lukeivers** [comment]
I have two cases that I've replaced it with.  Well, one and then that one plus a little extra.

So, I found a lot of references to AsyncDisplayKit but didn't want to have to re-write my app to take advantage of what they offer.

However, the underlying library used by AsyncDisplayKit to manage image loading in the background is called PINRemoteImage.

I am using PINRemoteImage, and in one case (a table with extremely high resolution images that needs to still be able to scroll quickly), I actually refactored the controller to use AsyncDisplayKit.

The other one that I'd recommend that seemed to work very well (but didn't handle progressive JPEGs, which was a hard requirement for me) was Kingfisher.

**Pull request merged**
