### PR TITLE
xcode 10 + swift 4.2

### PR DESCRIPTION
**Pull request by aporat**

### CODE REVIEW

**Comment by dorsegal** [comment]
any updates about this PR?

**Comment by vade** [comment]
Seconded, it would be great to merge to get 4.2 support!

**Comment by j-j-m** [comment]
pretty please.

**Comment by cbess** [comment]
@joanromano Will you be able to merge this soon?

**Comment by joanromano** [comment]
Hi, I am not a maintainer anymore but if you guys think this is fine to go I am more than happy to merge it

**Comment by aporat** [comment]
@joanromano I'll be happy if these changes can be merged. nothing too major here and I've been using it for awhile now

**Pull request merged**
