### PR TITLE
Updated to swift 5 and fixed all warnings.

### PR DESCRIPTION
**Pull request by kevnm67**
This PR updates HanekeSwift to swift 5.0 and Xcode 10.2. 

[Updated]
- Updates Swift Language Version to swift 5 and Xcode 10.2.
- Travis.yml to use Xcode 10.2
- Podspec bump.

[Fixed]
- All compiler warnings.

### CODE REVIEW

**Comment by elliothimmelfarb** [comment]
Let's do this!

**Comment by elliothimmelfarb** [comment]
@kevnm67 Thanks for putting this together. Any thoughts on when this might be accepted?

**Comment by kevnm67** [comment]
@elliothimmelfarb Happy to do it. 
To answer your question: Not sure.  It's up to the maintainers.  I'd love to get this in as well.  Currently, I'm having Carthage use the forked version, which isn't ideal.

**Comment by kevnm67** [comment]
@joanromano thoughts on this PR?

**Comment by joanromano** [comment]
@kevnm67 sorry for the delay, I'll have a look asap. And by the way thanks for your effort, really appreciated

**Comment by kevnm67** [comment]
@joanromano No problem.  Happy to contribute!

**Comment by joanromano** [comment]
Looks good to me thanks @kevnm67 !

**Comment by kevnm67** [comment]
@joanromano Awesome!

**Pull request merged**
