### PR TITLE
Issue #115 - Synchronise access to UIImage with data to avoid crash

### PR DESCRIPTION
**Pull request by paulosotu**
It seems that UIImage with data constructor is not thread safe. Having
two simultaneous threads accessing it was creating the Issue #115
reported already by many. Added NSLock to synchronise access between
the several threads…

### CODE REVIEW

**Comment by gilesvangruisen** [comment]
:+1: Looks good, can we get this merged?

**Comment by dcharbonnier** [comment]
for me it seams strange to do it at this level, why not directly when instantiating the UIImage ?
And yes, it seams that this is the problem, from the documentation :
>You can not assume that this method is thread safe.

**Comment by paulosotu** [comment]
@dcharbonnier agreed, just refactored to get the lock into the UIImage extension and created safeImageWithData.

**Comment by dcharbonnier** [comment]
hope @hpique can review it ;-)

**Comment by peacemoon** [comment]
+1 to merge this

**Comment by cmcnab** [comment]
+1 from me too.  I was getting this issue pretty consistently and tried that PR and it's been stable so far.

**Comment by hwaxxer** [comment]
:+1:

**Comment by erikolsson** [comment]
+1 from me too!

**Comment by hpique** [comment]
Thanks for sharing @paulosotu.

This is so annoying. UIImage is supposed to be thread-safe. Yet, there is [anecdotical evidence](http://stackoverflow.com/a/19473280) that `imageWithData:` has issues.

I might merge this anyway as you and more are reporting problems. It's frustrating that I have never been able to reproduce #115.

@dcharbonnier The documentation you quoted is for `imageNamed`.

**Comment by hpique** [comment]
@paulosotu The thing is that if `imageWithData:` is indeed buggy, then this wouldn't solve the issue entirely. There's nothing preventing some other part of your app to use `imageWithData:` at the same time than Haneke. 

The only solution would be to always use `imageWithData:` from the main thread, which defeats the purpose of creating images in background. Arg.

**Comment by paulosotu** [comment]
@hpique Yes, it forces anyone to use a synchronise imageWithData... and yes doesn't make any sense to use imageWithData only from the Main thread since background fetching would be one of its main usage, but the only way to really fix the issue is to wait on a fix from Apple... 

I do believe this to be a bug introduce on iOS 8 but haven't try to replicate it on iOS 9 to check if it the behaviour is still the same. A good way to replicate this is to create a while cycle that creates a worker thread that reads an image file and instantiate a UIImage using imageWithData.

**Comment by hpique** [comment]
@paulosotu Mind sharing the code you used to replicate the bug?

**Comment by paulosotu** [comment]
@hpique sorry for the late reply but I used something like:

let data = NSData(contentsOfURL: NSURL(string: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTf4P0V2TrszykwPguyeulcSt4vwQPcvvWKKq_RePhUUVFoHevG9lw8GVcw")!)
    var test: Array<UIImage> = []
    let lock = NSLock()
    for i in 0...10000 {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), { () -> Void in
            NSLog("Processing \(i)")
            let a = UIImage(data:data!)
            NSLog("Processed \(i)")
            lock.lock()
            test.append(a!)
            test.removeLast()
            lock.unlock()
        })

This usually do the trick at replicating the crash inside UIImage...

**Comment by JohnCoates** [comment]
great PR @paulosotu, I was getting this crash frequently

**Comment by vlas-voloshin** [comment]
I believe there's a deeper issue: in my app, I'm getting intermittent crashes in `UIImage.dealloc` being called on background thread. This might be caused by temporary `UIImage` instances created during background processing, and then deallocated when the GCD worker thread autorelease pool is drained.

**Comment by hwaxxer** [comment]
This PR may not be a silver bullet (will still crash if you're accessing UIImage from other processes), but it reduces crashes by a significant amount.

**Comment by dcharbonnier** [comment]
I don't think anybody use HanekeSwift without this patch, so even if it's not perfect it really deserve to be merged until someone else find a better fix

**Comment by hpique** [comment]
Finally merged this. Thanks @paulosotu!

Worth mentioning that this doesn't fully fix the issue unless you make sure that your whole app uses `UImage.convertFromData` with initialization an image from data.

Hopefully Apple will fix this bug sooner than later and we can remove this workaround.

**Pull request merged**
