### PR TITLE
Specify swift version to satisfy carthage

### PR DESCRIPTION
**Pull request by siemensikkema**

### CODE REVIEW

**Comment by kirillyakimovich** [comment]
Same unmerged PR since july :)

**Comment by dcharbonnier** [comment]
I can't merge with a failing build

**Comment by BrettRToomey** [comment]
Any updates on this?

**Comment by dcharbonnier** [comment]
should be of with the master branch (swift 4 support) since a week, open an issue with the full error if now @BrettRToomey

**Pull request closed without merging**
