### PR TITLE
caculate basePath only once in DiskCache

### PR DESCRIPTION
**Pull request by CaptainTeemo**
finished a TODO in class `DiskCache` line 17

### CODE REVIEW

**Comment by dcharbonnier** [comment]
@CaptainTeemo what do you think ?

**Comment by CaptainTeemo** [comment]
@dcharbonnier if we put that `calculate` stuff in getter of static var
```swift
public static var staticBasePath: String {
    let cachesPath = NSSearchPathForDirectoriesInDomains(NSSearchPathDirectory.CachesDirectory, NSSearchPathDomainMask.UserDomainMask, true)[0]
    let hanekePathComponent = HanekeGlobals.Domain
    let basePath = (cachesPath as NSString).stringByAppendingPathComponent(hanekePathComponent)
    return basePath
}
```
 it will be executed multiple times too.

So I think you mean

```swift
public static var staticBasePath: String {
    return privateBasePath
}
```

but that's the same as a class function if `basePath` will never be changed.

```swift
public class func basePath() -> String {
    return privateBasePath
}
```

if I was wrong please tell
thx 😆

**Comment by dcharbonnier** [comment]
why not a lazy initialization ?

image

**Comment by CaptainTeemo** [comment]
omg I thought a lazy init variable must be declared with `lazy`.

thanks man

**Pull request closed without merging**
