### PR TITLE
Main queue replaced with custom serial queue

### PR DESCRIPTION
**Pull request by DanielOberg**
Main queue replaced with custom serial queue.

Fixes issue Haneke/HanekeSwift#238

### CODE REVIEW

**Comment by iDad** [comment]
I would love to see this integrated. I've applied it to the current version locally as I was running into issues caused by Haneke synchronizing on main.

**Comment by bartoszhernas** [comment]
Is there a plan to merge this?

**Comment by dcharbonnier** [comment]
can you propose this for the branch swift-3 so I can merge ?

**Comment by dcharbonnier** [comment]
anyone to make this compatible with the swift-3 branch ?

**Comment by bartoszhernas** [comment]
Just did it in #396

**Pull request closed without merging**
