### PR TITLE
[FIX] SWIFT_VERSION field is added

### PR DESCRIPTION
**Pull request by kirillyakimovich**
new filed added to project.pbxproj

### CODE REVIEW

**Comment by kirillyakimovich** [comment]
Test is failing as there is no simulator to test, it is not related to provided changes

**Comment by dcharbonnier** [comment]
please make the build pass and reopen if needed

**Comment by kirillyakimovich** [comment]
Cannot rerun Travis build

**Comment by dcharbonnier** [comment]
thx, the master is now using swift 4 anyway

**Pull request closed without merging**
