### PR TITLE
Feature/swift 3

### PR DESCRIPTION
**Pull request by filippovdev**
Its compiling and working for me.

### CODE REVIEW

**Comment by dcharbonnier** [comment]
Thx but we don't merge if the tests are broken

**Comment by filippovdev** [comment]
@dcharbonnier but please look inside log, it sad that "is unknown attribute 'escaping'" , something wrong with Travis configuration, he didn't pass any Swift 3.0 code.

**Comment by StupidDutchName** [comment]
How / where can I contribute to this merge request to speed up Swift 3 release?

**Comment by dcharbonnier** [comment]
please submit PR to feature/swift-3

**Pull request closed without merging**
